language: python

python:
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"

install:
  - "pip install . pytest pytest-cov"

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

script: py.test lazycontract --cov=lazycontract --cov-report xml

after_script:
  - ./cc-test-reporter after-build --exit-code $EXIT_CODE
